name: Run Unit Tests

on:
  pull-request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run unit tests
      run: |
        pytest
